namespaces:
  =: io.murano.apps.netsfc.plugin
  std: io.murano
  res: io.murano.resources
  sys: io.murano.system


Name: NetSFCApp

Extends: std:Application

Properties:
  portPair:
    Contract: $.class(res.PortPair).notNull()

  portPairGroup:
    Contract: $.class(res:PortPairGroup).notNull()

  flowClassifier:
    Contract: $.class(res:FlowClassifier).notNull()

  portChain:
    Contract: $.class(res:PortChain).notNull()

Methods:
  deploy:
    Body:
      $.portPair.deploy()
      $.portPair_group.deploy()
      $.flowClassifier.deploy()
      $.portChain.deploy()

